from .AlignAverageWidget import AlignAverageWidget
from .AlignmentLineWidget import AlignmentLineWidget
from .AlignXYWidget import AlignXYWidget
from .AutofocusWidget import AutofocusWidget
from .basewidgets import WidgetFactory
from .BeadRecWidget import BeadRecWidget
from .ConsoleWidget import ConsoleWidget
from .EtSTEDWidget import EtSTEDWidget
from .EtMonalisaWidget import EtMonalisaWidget
from .FFTWidget import FFTWidget
from .FocusLockWidget import FocusLockWidget
from .ImageWidget import ImageWidget
from .LaserWidget import LaserWidget
from .LeicaStandWidget import LeicaStandWidget
from .MotCorrWidget import MotCorrWidget
from .PositionerWidget import PositionerWidget
from .RecordingWidget import RecordingWidget
from .SLMsWidget import SLMsWidget
from .ScanWidgetBase import ScanWidgetBase
from .ScanWidgetMoNaLISA import ScanWidgetMoNaLISA
from .ScanWidgetPointScan import ScanWidgetPointScan
from .ScanWidgetAdvanced import ScanWidgetAdvanced
from .RotationScanWidget import RotationScanWidget
from .RotatorWidget import RotatorWidget
from .SettingsWidget import SettingsWidget
from .SLMWidget import SLMWidget
from .TilingWidget import TilingWidget
from .ULensesWidget import ULensesWidget
from .ViewWidget import ViewWidget
from .WatcherWidget import WatcherWidget
from .BFTimelapseWidget import BFTimelapseWidget
from .FlipMirrorWidget import FlipMirrorWidget
# from .EtWidget import EtWidget # Current prototype on old Monalisa machine needs rework, hardcoded paths, not tracked, etc. for now commented!
