# This is heavily based on the napari dockerfile
FROM --platform=linux/amd64 ubuntu:22.04 AS napari
# if you change the Ubuntu version, remember to update
# the APT definitions for Xpra below so it reflects the
# new codename (e.g. 20.04 was focal, 22.04 had jammy)

ENV TZ=Europe/Berlin
ARG DEBIAN_FRONTEND=noninteractive
ARG IMSWITCH_COMMIT=master

# Install system dependencies
# install python resources + graphical libraries used by qt and vispy
RUN apt-get update
RUN apt-get install -qqy \
    libxml2-dev \
    libxslt-dev \
    git \
    wget \
    build-essential \
    python3.9 \
    python3-pip \
    mesa-utils \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libfontconfig1 \
    libxrender1 \
    libdbus-1-3 \
    libxkbcommon-x11-0 \
    libxi6 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-xinerama0 \
    libxcb-xinput0 \
    libxcb-xfixes0 \
    libxcb-shape0
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Clone necessary repositories and install dependencies
RUN git clone https://github.com/openUC2/ImSwitch /ImSwitch && \
    git clone https://github.com/openUC2/UC2-REST /UC2-REST && \
    git clone https://github.com/openUC2/ImSwitchConfig /ImSwitchConfig

# Install ImSwitch
WORKDIR /ImSwitch
RUN git checkout ${IMSWITCH_COMMIT}
RUN pip3 install -e .

# Install UC2-REST
WORKDIR /UC2-REST
RUN pip3 install -e .



ENTRYPOINT ["python3", "-m", "imswitch"]

# now we need to run imswitch by running "python3 -m imswitch"
CMD ["python3", "-m", "imswitch"]
